# ai2_arc evaluation Configuration
defaults: "eval.yaml"

generation:
  model_name: "Qwen/Qwen3-8B"
  vllm_cfg:
    max_model_len: 8192

data:
  prompt_file: "examples/prompts/gpqa.txt"
  dataset_name: "ai2_arc"
  subset: "ARC-Challenge"
  split: "train"

env:
  math:
    worker_type: "english_multichoice"
