# IFEval evaluation Configuration
defaults: "eval.yaml"

generation:
  model_name: "Qwen/Qwen3-8B"
  vllm_cfg:
    max_model_len: 8192

data:
  prompt_file: null
  dataset_name: "ifeval"

env:
  math:
    worker_type: "instruction_following"
