# Math evaluation Configuration
defaults: "gpqa.yaml"

data:
  prompt_file: "examples/prompts/if_cot.txt"
  dataset_name: "ifeval"

env:
  math:
    worker_type: "instruction_following"

generation:
  model_name: "/home/tangyoubao_google_com/nemo-rl/results/qwen3_8b_both_8192_postfix/step_8562/hf"
  enable_thinking: true
  vllm_cfg:
    max_model_len: 8192