# Math evaluation Configuration
defaults: "gpqa.yaml"

data:
  prompt_file: "examples/prompts/if_cot.txt"
  dataset_name: "ifeval"

env:
  math:
    worker_type: "instruction_following"

generation:
  model_name: "google/gemma-3-27b-pt"
  # enable_thinking: true
  vllm_cfg:
    max_model_len: 4096