# Math evaluation Configuration
defaults: "gpqa.yaml"

generation:
  model_name: "Qwen/Qwen2.5-7B-Instruct"

data:
  prompt_file: "examples/prompts/cot.txt"
  dataset_name: "math"

env:
  math:
    worker_type: "math"
