# MBPP evaluation Configuration
defaults: "eval.yaml"

data:
  prompt_file: "examples/prompts/mbpp.txt"
  dataset_name: "mbpp"
  code_exe_dir: "/tmp/logs"

generation:
  model_name: "Qwen/Qwen2.5-7B-Instruct"
  vllm_cfg:
    max_model_len: 4096

env:
  env_type: "code"
  code:
    num_workers: 8
    terminate_on_evaluation: true
    worker_type: "python_code_verify"
