# SWE-Bench_Verified evaluation Configuration
defaults: "eval.yaml"

data:
  dataset_name: "swebench_verified_oracle"

generation:
  vllm_cfg:
    max_model_len: 131072
    gpu_memory_utilization: 0.9
    tensor_parallel_size: 1

env:
  math:
    verifier_type: "swebench_verified"
    verifier_metadata_key: "ground_truth"

cluster:
  gpus_per_node: 4
  num_nodes: 1
