# SWE-Bench_Verified evaluation Configuration
defaults: "eval.yaml"

data:
  dataset_name: "swebench_verified_oracle"

generation:
  vllm_cfg:
    max_model_len: 32768

env:
  math:
    verifier_type: "swebench_verified"
    verifier_metadata_key: "ground_truth"
