repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: end-of-file-fixer
      types_or: [python, pyi] # Only include Python files.
    - id: trailing-whitespace
      types_or: [python, pyi] # Only include Python files.

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.9" # Use the appropriate version
    hooks:
    - id: ruff
      args: ["--fix"]
    - id: ruff
      args: ["check", "--select", "I", "--fix"]
    - id: ruff-format

  - repo: local
    hooks:
      - id: no-underscore-md
        name: "Disallow '_' in Markdown filenames"
        language: system
        entry: |
          bash -c '
            # Report the offending files
            echo "[pre-commit] ERROR: Found Markdown files with underscores:" >&2
            for file in "$@"; do
              echo "  - $file (use hyphens instead)" >&2
            done
            exit 1
          '
        files: '.*\/[^\/]*_[^\/]*\.md$'
        exclude: '^\.github/'
        types: [file]

  - repo: local
    hooks:
      - id: pyrefly-typecheck
        name: pyrefly check
        entry: uv run --group dev pyrefly check
        types_or: [python, pyi]
        language: system
        pass_filenames: false # Pyrefly reads config & project roots itself.
        args: []
        require_serial: true
        additional_dependencies: []
        minimum_pre_commit_version: "2.9.2"
