sft:
  max_num_epochs: 1
  max_num_steps: 20
  val_period: 10
  val_batches: 8
  val_global_batch_size: 32
  val_micro_batch_size: 1
  val_at_start: true
  seed: 42
checkpointing:
  enabled: true
  checkpoint_dir: results/sft-qwen2.5-32b-4n8g-fsdp2tp8sp-actckpt
  metric_name: val_loss
  higher_is_better: false
  keep_top_k: 3
  save_period: 10
  checkpoint_must_save_by: null
policy:
  model_name: Qwen/Qwen2.5-32B
  tokenizer:
    name: Qwen/Qwen2.5-32B
    chat_template: '{% for message in messages %}{%- if message[''role''] == ''system''  %}{{''Context: '' + message[''content''].strip()}}{%- elif message[''role''] == ''user''  %}{{'' Question: '' + message[''content''].strip() + '' Answer:''}}{%- elif message[''role''] == ''assistant''  %}{{'' '' + message[''content''].strip()}}{%- endif %}{% endfor %}'
  train_global_batch_size: 32
  train_micro_batch_size: 1
  max_total_sequence_length: 16000
  precision: bfloat16
  dtensor_cfg:
    enabled: true
    cpu_offload: false
    sequence_parallel: true
    activation_checkpointing: true
    tensor_parallel_size: 8
    context_parallel_size: 1
    custom_parallel_plan: null
  dynamic_batching:
    enabled: false
  sequence_packing:
    enabled: false
    train_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.train_micro_batch_size}}
    algorithm: "modified_first_fit_decreasing"
    sequence_length_round: 64
  make_sequence_length_divisible_by: 8
  max_grad_norm: 1
  optimizer:
    name: torch.optim.AdamW
    kwargs:
      lr: 5e-06
      weight_decay: 0.1
      betas:
        - 0.9
        - 0.98
      eps: 1e-05
      foreach: false
      fused: false
data:
  max_input_seq_length: 16000
  dataset_name: squad
  add_bos: true
  add_eos: true
  add_generation_prompt: false
  shuffle: true
logger:
  log_dir: logs/sft-qwen2.5-32b-4n8g-fsdp2tp8sp-actckpt
  wandb_enabled: true
  tensorboard_enabled: true
  mlflow_enabled: false
  monitor_gpus: true
  num_val_samples_to_print: 0  # Number of validation samples to pretty print on terminal
  wandb:
    project: nemo-rl
    name: sft-qwen2.5-32b-4n8g-fsdp2tp8sp-actckpt
  tensorboard:
    log_dir: tb_logs-sft-dev-squad
  gpu_monitoring:
    collection_interval: 10
    flush_interval: 10
cluster:
  gpus_per_node: 8
  num_nodes: 4
