# Rejection sampling configuration for Qwen3 32B model (no thinking mode)

defaults: "qwen3_8b_science_sampling.yaml"

generation:
  # temperature: 0.0
  # top_p: 0.8
  # top_k: 1
  model_name: "Qwen/Qwen3-32B"
  # enable_thinking: false