# Rejection sampling configuration for Qwen3 32B model (thinking mode)

defaults: "qwen3_14b_math_no_thinking.yaml"

rejection_sampling:
  num_tests_per_prompt: 3
  metric: "pass@1,3"

generation:
  temperature: 0.6
  top_p: 0.95
  model_name: "Qwen/Qwen3-32B"
  enable_thinking: true
  vllm_cfg:
    max_model_len: 38912