# Rejection sampling configuration for Qwen3 8B model (thinking mode)

defaults: "qwen3_14b_math_no_thinking.yaml"

rejection_sampling:
  num_tests_per_prompt: 5
  metric: "pass@1,3,5"

generation:
  enable_thinking: true
  temperature: 0.6
  top_p: 0.95
  model_name: "Qwen/Qwen3-8B"
  vllm_cfg:
    max_model_len: 32768

data:
  prompt_file: "examples/prompts/arc_agi.txt"
  dataset_name: "arc_agi"
  split: "training"

env:
  math:
    worker_type: "arc_agi"