# Rejection sampling configuration for Qwen3 14B model (no-thinking mode)

defaults: "qwen3_14b_math_no_thinking.yaml"

rejection_sampling:
  num_tests_per_prompt: 10
  metric: "pass@1,5,10"

generation:
  vllm_cfg:
    max_model_len: 8192

data:
  data_paths: "logs/nemotron/Qwen/fullset/consensus_examples.parquet"
  problem_key: "problems"
  answer_key: "expected_answers"
  dataset_name: "local_science"
  split: "train"
  file_format: "parquet"
  prompt_file: null
  system_prompt_file: "examples/prompts/nemotron_science.txt"