# Rejection sampling configuration for Qwen3 14B model (thinking mode)

defaults: "qwen3_14b_no_thinking.yaml"

rejection_sampling:
  num_tests_per_prompt: 3
  metric: "pass@1,3"

generation:
  temperature: 0.6
  top_p: 0.95
  enable_thinking: true
  vllm_cfg:
    max_model_len: 38912

data:
  dataset_name: "ifeval_like"
  source: "filtered"
  prompt_file: "examples/prompts/if_cot.txt"

env:
  math:
    num_workers: 8
    verifier_type: "instruction_following"
    worker_type: "instruction_following"