# Rejection sampling configuration for Qwen3 14B model (no-thinking mode)

defaults: "qwen3_14b_code_no_thinking.yaml"

rejection_sampling:
  num_tests_per_prompt: 3
  metric: "pass@1,3"

generation:
  enable_thinking: true
  temperature: 0.6
  top_p: 0.95
  vllm_cfg:
    max_model_len: 38912
