# Reference run: https://wandb.ai/gmayanksharan-google/cirrus/runs/b49dh204
# In order to train with this config, please copy the data from /mnt to your log directory. For example,
# cp -r /gcs/cloud-nas-hns-data/cirrus0.0/openr1_math_*qwen3_14b_thinking/ $JOB_ID/ray-logs/app_logs/
# cp -r /gcs/cloud-nas-hns-data/cirrus0.1/sciq_qwen3_14b_mcq_thinking/ $JOB_ID/ray-logs/app_logs/
#
# Example launch command:
# uv run examples/run_sft.py --config examples/configs/cirrus/official/cirrus0.1-14b-thinking-megatron.yaml \
# cluster.num_nodes=4 \
# cluster.gpus_per_node=8 \
# logger.log_dir=$LOCAL_LOG_DIR_IN_CONTAINER \
# checkpointing.checkpoint_dir=${CKPT_LOCAL_DIR}/cirrus0p1_14b_thinking_megatron \
# logger.wandb.name=cirrus0p1_14b_thinking_megatron
sft:
  max_num_epochs: 1
  max_num_steps: 2791
  val_period: 100
  val_batches: 32
  val_global_batch_size: 32
  val_micro_batch_size: 2
  val_at_start: true
  seed: 42
checkpointing:
  enabled: true
  checkpoint_dir: "results/sft_qwen3_14b_openr1_math_mcq_distilled_thinking_megatron"
  metric_name: val_loss
  higher_is_better: false
  save_period: 1000
  keep_top_k: null
  checkpoint_must_save_by: null
policy:
  model_name: "Qwen/Qwen3-14B-Base"
  tokenizer:
    name: "Qwen/Qwen3-14B"
    chat_template: "default"
  train_global_batch_size: 32
  train_micro_batch_size: 1
  logprob_batch_size: 1
  max_total_sequence_length: 32768
  precision: bfloat16

  dtensor_cfg:
    enabled: false
  
  megatron_cfg:
    enabled: true
    empty_unused_memory_level: 1
    activation_checkpointing: true
    converter_type: "Qwen2ForCausalLM"
    tensor_model_parallel_size: 8
    expert_tensor_parallel_size: 1
    expert_model_parallel_size: 1
    pipeline_model_parallel_size: 1
    num_layers_in_first_pipeline_stage: null
    num_layers_in_last_pipeline_stage: null
    context_parallel_size: 1
    pipeline_dtype: ${policy.precision}
    sequence_parallel: true
    freeze_moe_router: true
    moe_router_dtype: "fp64"
    moe_router_load_balancing_type: "none" # "seq_aux_loss" causes logprob error divergence for grpo
    moe_router_bias_update_rate: 0.0 # by default, disable bias updates for grpo
    #gives ~20% training perf speedup with sequence packing 
    apply_rope_fusion: True

    optimizer:
      optimizer: "adam"
      lr: 1.82e-05
      min_lr: 1.82e-6
      weight_decay: 0.1
      bf16: true
      fp16: false
      params_dtype: "float32"

      #adam
      adam_beta1: 0.9
      adam_beta2: 0.95
      adam_eps: 1e-6

      #distributed optimizer
      use_distributed_optimizer: true
      use_precision_aware_optimizer: true

      clip_grad: 1.0
      optimizer_cpu_offload: false
      optimizer_offload_fraction: 0.0

    scheduler:
      start_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      end_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      weight_decay_incr_style: "constant"
      lr_decay_style: "cosine"
      lr_decay_iters: 2791
      lr_warmup_iters: 200
      lr_warmup_init: 1.82e-7

    distributed_data_parallel_config:
      grad_reduce_in_fp32: false
      overlap_grad_reduce: true
      overlap_param_gather: true
      average_in_collective: true
      use_custom_fsdp: false
      data_parallel_sharding_strategy: "optim_grads_params"

  dynamic_batching:
    enabled: False

  sequence_packing:
    enabled: True
    train_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.train_micro_batch_size}}
    algorithm: "modified_first_fit_decreasing"
    sequence_length_round: 64

  make_sequence_length_divisible_by: ${policy.megatron_cfg.tensor_model_parallel_size}
  optimizer: null

data:
  max_input_seq_length: ${policy.max_total_sequence_length}
  dataset_name: "dataset_mixture"
  # the original dataset is located in /mnt/dataset/cirrus0.0/
  mixture:
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_math_amc_aime_qwen3_14b_thinking/train-unboxed*"
      samples: 703
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_math_aops_forum_qwen3_14b_thinking/train-unboxed*"
      samples: 6264
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_math_cn_contest_qwen3_14b_thinking/train-unboxed*"
      samples: 7396
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_math_inequalities_qwen3_14b_thinking/train-unboxed*"
      samples: 661
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_math_number_theory_qwen3_14b_thinking/train-unboxed*"
      samples: 214
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_math_olympiads_qwen3_14b_thinking/train-unboxed*"
      samples: 44330
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/openr1_math_olympiads_ref_qwen3_14b_thinking/train-unboxed*"
      samples: 498
      additional_kwargs:
        split: "train"
    - file_format: "parquet"
      name_or_paths: "/tmp/logs/sciq_qwen3_14b_mcq_thinking/train-augmented*"
      samples: 4000
      additional_kwargs:
        split: "train"
    - file_format: "huggingface"
      name_or_paths: "allenai/tulu-3-sft-personas-instruction-following"
      samples: 29980
      additional_kwargs:
        split: "train"
  add_bos: true
  add_eos: true
  add_generation_prompt: false
logger:
  log_dir: "logs/sft_qwen3_14b_openr1_math_mcq_distilled_thinking_megatron"
  wandb_enabled: true
  tensorboard_enabled: false
  mlflow_enabled: false
  monitor_gpus: true
  wandb:
    project: cirrus
    name: sft_qwen3_14b_openr1_math_mcq_distilled_thinking_megatron
  gpu_monitoring:
    collection_interval: 30
    flush_interval: 30
cluster:
  gpus_per_node: 8
  num_nodes: 4
